export const CLIENT_METHODS = {
  user: ['createUser', 'getUser', 'listUsers', 'getOrCreateUser', 'updateUser', 'deleteUser'],
  conversation: [
    'createConversation',
    'getConversation',
    'listConversations',
    'getOrCreateConversation',
    'updateConversation',
    'deleteConversation',
  ],
  event: ['createEvent', 'getEvent', 'listEvents'],
  message: ['createMessage', 'getOrCreateMessage', 'getMessage', 'updateMessage', 'listMessages', 'deleteMessage'],
  file: ['createFile', 'getFile', 'downloadFile', 'deleteFile', 'listFiles'],
  state: ['getState', 'setState', 'patchState'],
  hub: ['listPublicIntegrations', 'getPublicIntegrationById', 'getPublicIntegration'],
  action: ['callAction'],
  bot: [
    'createBot',
    'updateBot',
    'transferBot',
    'listBots',
    'getBot',
    'deleteBot',
    'getBotLogs',
    'getBotWebchat',
    'getBotAnalytics',
  ],
  integration: [
    'createIntegration',
    'updateIntegration',
    'listIntegrations',
    'getIntegration',
    'getIntegrationLogs',
    'getIntegrationByName',
    'deleteIntegration',
  ],
  workspace: [],
}
