export const SAMPLE_MESSAGES: string[] = [
  "Get a list of users that have interacted with the bot",
  "Get a list of users that have talked to my bot",
  "Get the latest conversation",
  "Get a list of users that talked to my bot",
  "What was the last message that user x sent",
  "Get the last message that user x sent",
  "Get the list of all the files that the userx uploaded",
  "Get the list of all the files that the userx has sent",
  "How many members are in my workspace",
  "Delete the users that have not interacted with the bot in the last 30 days",
  "What is the most used integration in my workspace",
];

export const CLIENT_METHODS: Record<string, string[]> = {
  user: [
    "createUser",
    "deleteUser",
    "getOrCreateUser",
    "getUser",
    "listUsers",
    "updateUser",
  ],
  conversation: [
    "createConversation",
    "deleteConversation",
    "getConversation",
    "getOrCreateConversation",
    "listConversations",
    "updateConversation",
  ],
  workspace: [
    "createWorkspaceMember",
    "deleteWorkspaceMember",
    "getWorkspace",
    "listWorkspaceMembers",
    "listWorkspaces",
    "updateWorkspace",
    "updateWorkspaceMember",
  ],
  event: ["createEvent", "getEvent", "listEvents"],
  message: [
    "createMessage",
    "deleteMessage",
    "getMessage",
    "getOrCreateMessage",
    "listMessages",
    "updateMessage",
  ],
  file: ["createFile", "deleteFile", "downloadFile", "getFile", "listFiles"],
  state: ["getState", "patchState", "setState"],
  action: ["callAction"],
  integration: [
    "configureIntegration",
    "createIntegration",
    "deleteIntegration",
    "getIntegration",
    "getIntegrationByName",
    "getIntegrationLogs",
    "getPublicIntegration",
    "getPublicIntegrationById",
    "listIntegrations",
    "listPublicIntegrations",
    "updateIntegration",
  ],
  bot: [
    "createBot",
    "deleteBot",
    "getBot",
    "getBotAnalytics",
    "getBotLogs",
    "getBotWebchat",
    "introspect",
    "listBots",
    "transferBot",
    "updateBot",
  ],
};
