name: Deploy Documentation Staging
on:
  push:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  documentation:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/build-documentation
        with:
          unleash-url: ${{ vars.UNLEASH_URL }}
          unleash-app-name: ${{ vars.UNLEASH_APP_NAME }}
          unleash-client-key: ${{ vars.UNLEASH_CLIENT_KEY }}
          bot-url: ${{ vars.BOT_URL }}

      - uses: botpress/gh-actions/deploy/s3@v2
        with:
          aws-role: ${{ secrets.AWS_DOCUMENTATION_UPLOAD_ROLE }}
          destination: s3://${{ secrets.AWS_DOCUMENTATION_BUCKET_NAME }}/docs
          cloudfront-distribution-id: ${{ secrets.AWS_DOCUMENTATION_CLOUDFRONT_DISTRIBUTION_ID  }}
          cloudfront-invalidation-prefix: '/docs/*'
          source: ./out
