name: Generate and Upload Botpress API reference to ReadMe

on:
  push:
    branches:
      - main

jobs:
  generate_and_upload_to_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script to generate file
        run: node ./scripts/formatBpDocs.js

      - name: Upload to Readme
        uses: readmeio/rdme@v8
        with:
          rdme: openapi ./scripts/botpress-openapi-output.json --key=${{ secrets.README_API_KEY }} --id=668589cbef56700030f95925
